// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0cZdTXNYdvrCQVqPEsWxXP_lIDtLrjA8',
    appId: '1:164491716587:web:848c290c97c53b4a949bae',
    messagingSenderId: '164491716587',
    projectId: 'epharmacy-c8fe8',
    authDomain: 'epharmacy-c8fe8.firebaseapp.com',
    storageBucket: 'epharmacy-c8fe8.firebasestorage.app',
    measurementId: 'G-WGKGKXDVGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJmpWLtRVb0eqD9aUWVajCM-RUrqaOZoE',
    appId: '1:164491716587:android:ecda06123a24584b949bae',
    messagingSenderId: '164491716587',
    projectId: 'epharmacy-c8fe8',
    storageBucket: 'epharmacy-c8fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJX3r3w-EDZfMocQEhh6Q14U1KD0mIB_A',
    appId: '1:164491716587:ios:c471c9a140abca9a949bae',
    messagingSenderId: '164491716587',
    projectId: 'epharmacy-c8fe8',
    storageBucket: 'epharmacy-c8fe8.firebasestorage.app',
    iosBundleId: 'com.example.epharmacy',
  );
}
